# Generated by Django 3.1.2 on 2021-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieImage', models.ImageField(null=True, upload_to='web2app/movieImage', verbose_name='')),
                ('movieName', models.CharField(max_length=50)),
                ('movieSize', models.FloatField(default=0)),
            ],
        ),
    ]
