# Generated by Django 3.1.2 on 2021-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='movieUrl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
