# Generated by Django 3.1.2 on 2021-03-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0002_moviemodel_movieurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='movieUrl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
