# Generated by Django 3.1.2 on 2021-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0003_auto_20210325_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='movieUrl',
            field=models.URLField(),
        ),
    ]
