# Generated by Django 3.1.2 on 2021-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0004_auto_20210325_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='movieUrl',
            field=models.URLField(max_length=1000),
        ),
    ]
