# Generated by Django 3.1.2 on 2021-03-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0005_auto_20210325_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='movieImage',
        ),
    ]
