# Generated by Django 3.1.2 on 2021-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0006_remove_moviemodel_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='movieVideo',
            field=models.FileField(null=True, upload_to='web2app/movieImage/videos', verbose_name=''),
        ),
    ]
